name: '60711'
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.12
  - pandas=1.1.2
  - numpy=1.19.1
  - numpy-base=1.19.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - jupyterlab
  - tqdm
  - pip:
    - memory-profiler